#\!/bin/bash

is_weekend() {
    local date=$1
    local day_of_week=$(date -d "$date" +%u)
    [ $day_of_week -ge 6 ]
}

is_holiday() {
    local date=$1
    local holidays=$2
    local month=$(date -d "$date" +%m)
    local day=$(date -d "$date" +%d)
    for holiday in "${holidays[@]}"; do
        if [ "$holiday" == "$month-$day" ]; then
            return 0
        fi
    done
    return 1
}

get_working_day_before() {
    local date=$1
    local holidays=$2
    local current_date=$(date -d "$date -1 day" +%Y-%m-%d)
    while is_weekend "$current_date" || is_holiday "$current_date" "${holidays[@]}"; do
        current_date=$(date -d "$current_date -2 day" +%Y-%m-%d)
    done
    echo "$current_date"
}

main() {
    # List of holidays (month-day)
    holidays=("12-21" "12-25" "12-26" "01-01" "01-29" "01-30" "01-31" "04-04" "04-18" "04-19" "04-21" "05-01" "05-05" "05-31" "07-01")

    # Reminder dates (month-day)
    today_dates=("10-25" "10-30" "11-04" "11-05" "11-06" "11-11" "11-12" "11-20" "11-22" "12-02" "12-20" "12-24" "01-02")

    # Generate crontab entries
    crontab_entries=("# Following items autogenerated\. Don't replace other CRON items")

    current_year=$(date +%Y)

    for today_date in "${today_dates[@]}"; do
        month_day=(${today_date//-/ })
        month=${month_day[0]}
        day=${month_day[1]}
        full_date="$current_year-$month-$day"

        # Calculate three working days before
        threedays_before=$(get_working_day_before "$(get_working_day_before "$full_date" "${holidays[@]}")" "${holidays[@]}")
        threedays_before_day=$(date -d "$threedays_before" +%d)
        threedays_before_month=$(date -d "$threedays_before" +%m)

        # Add twodays\.sh entry
        crontab_entries+=("0 0 $threedays_before_day $threedays_before_month * /home/id2/\.local/bin/twodays\.sh > /dev/null 2>&1")

        # Add today\.sh entry
        crontab_entries+=("0 0 $day $month * /home/id2/\.local/bin/today\.sh > /dev/null 2>&1")
    done

    # Print crontab entries
    for entry in "${crontab_entries[@]}"; do
        echo "$entry"
    done
}

main
